package com.agacostays.notification.enums;

public enum EmailTemplateCode { BOOKING_CONFIRMATION, BOOKING_APPROVED, BOOKING_CANCELLED, PAYMENT_SUCCESS, CHECKOUT_REMINDER, FEEDBACK, SALARY_CREDITED, SUPPORT_REQUEST, FOOD_DELIVERED }
