package com.agacostays.notification.enums;

public enum NotificationType { BOOKING_CONFIRMATION, BOOKING_APPROVED, BOOKING_CANCELLED, PAYMENT_SUCCESS, PAYMENT_FAILED, CHECKOUT_REMINDER, FOOD_DELIVERED, SUPPORT_REQUEST, FEEDBACK, SALARY_CREDITED, GENERAL }
