spring.application.name=branch-service
server.port=8083

spring.datasource.url=${BRANCH_DB_URL:jdbc:postgresql://localhost:5432/branch_db}
spring.datasource.username=${BRANCH_DB_USERNAME:postgres}
spring.datasource.password=${BRANCH_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET:c2VjdXJlLWFnYS1jb3N0YXlzLWF1dGgtc2VjcmV0LWtleS1mb3ItcHJvamVjdC0yMDI2}

app.clients.user-service-url=${USER_SERVICE_URL:http://localhost:8082}
app.clients.notification-service-url=${NOTIFICATION_SERVICE_URL:http://localhost:8090}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.storage.local-directory=${BRANCH_STORAGE_DIR:uploads}
app.storage.public-base-url=${BRANCH_PUBLIC_FILE_URL:http://localhost:8083/files}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

management.endpoints.web.exposure.include=health,info,metrics
logging.level.com.agacostays.branch=INFO
