package com.agacostays.payroll.service.impl;
import com.agacostays.payroll.audit.*;import com.agacostays.payroll.client.*;import com.agacostays.payroll.dto.request.*;import com.agacostays.payroll.dto.response.*;import com.agacostays.payroll.entity.*;import com.agacostays.payroll.enums.*;import com.agacostays.payroll.event.*;import com.agacostays.payroll.event.producer.*;import com.agacostays.payroll.exception.*;import com.agacostays.payroll.mapper.*;import com.agacostays.payroll.repository.*;import com.agacostays.payroll.service.*;import com.agacostays.payroll.validation.*;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import jakarta.transaction.Transactional;import java.math.*;import java.util.*;
@Service public class PayrollServiceImpl implements PayrollService{
 final PayrollRepository repo;final SalaryStructureRepository structures;final PayrollMapper mapper;final UserServiceClient users;final AttendanceServiceClient attendance;final PayrollCalculationService calc;final SalaryCreditService credit;final PayrollValidationService validation;final PayrollEventProducer producer;final PayrollAuditHelper audit;
 public PayrollServiceImpl(PayrollRepository r,SalaryStructureRepository s,PayrollMapper m,UserServiceClient u,AttendanceServiceClient a,PayrollCalculationService c,SalaryCreditService cr,PayrollValidationService v,PayrollEventProducer p,PayrollAuditHelper h){repo=r;structures=s;mapper=m;users=u;attendance=a;calc=c;credit=cr;validation=v;producer=p;audit=h;}
 @Transactional public List<PayrollResponse> generate(GeneratePayrollRequest r,Long actor){List<Long> ids=r.staffId()!=null?List.of(r.staffId()):users.getActiveStaffIds(r.branchId());if(ids.isEmpty())throw new BusinessRuleException("No staff found for payroll generation");return ids.stream().map(id->generateForStaff(id,r,actor)).toList();}
 @Transactional public PayrollResponse generateForStaff(Long staffId,GeneratePayrollRequest r,Long actor){Payroll old=repo.findByStaffIdAndMonthAndYear(staffId,r.month(),r.year()).orElse(null);if(old!=null)return mapper.toResponse(old);UserResponse u=users.getUser(staffId);Long branch=r.branchId()!=null?r.branchId():(u==null?null:u.branchId());if(branch==null)throw new BusinessRuleException("Branch is required");String role=u==null||u.role()==null?"STAFF":u.role();SalaryStructure s=structures.findByRoleNameIgnoreCaseAndStatus(role,SalaryStructureStatus.ACTIVE).stream().findFirst().orElseGet(()->structures.findByRoleNameIgnoreCaseAndStatus("STAFF",SalaryStructureStatus.ACTIVE).stream().findFirst().orElseThrow(()->new ResourceNotFoundException("Salary structure not found for role "+role)));AttendanceSummaryResponse ar=attendance.summary(staffId,r.month(),r.year());int wd=ar!=null&&ar.totalWorkingDays()!=null?ar.totalWorkingDays():Math.max(1,r.month()<=12?java.time.YearMonth.of(r.year(),r.month()).lengthOfMonth():26);if(ar==null)ar=new AttendanceSummaryResponse(staffId,r.month(),r.year(),wd,wd,0,0,0,BigDecimal.ZERO);var z=calc.calculate(s,ar,wd);Payroll p=Payroll.builder().branchId(branch).staffId(staffId).roleId(s.getRoleId()).department("UNKNOWN").month(r.month()).year(r.year()).totalWorkingDays(wd).presentDays(n(ar.presentDays())).absentDays(n(ar.absentDays())).halfDays(n(ar.halfDays())).leaveDays(n(ar.leaveDays())).basicSalary(z.basic()).hra(z.hra()).allowances(z.allowances()).bonus(z.bonus()).grossSalary(z.gross()).attendanceDeduction(z.attendanceDeduction()).otherDeductions(z.otherDeductions()).netSalary(z.net()).paymentStatus(PayrollStatus.GENERATED).paymentMode(parse(r.paymentMode())).remarks("Generated").generatedBy(actor).build();p=repo.save(p);producer.generated(new PayrollGeneratedEvent(p.getPayrollId(),p.getBranchId(),p.getStaffId(),p.getMonth(),p.getYear(),p.getNetSalary()));audit.record(new AuditLogRequest("PAYROLL_GENERATED",actor,p.getBranchId(),p.getPayrollId(),"period="+p.getMonth()+"/"+p.getYear()));return mapper.toResponse(p);}
 public PageResponse<PayrollResponse> search(Integer month,Integer year,Long branchId,int page,int size){int s=Math.min(Math.max(size,1),100);if(branchId!=null){Page<Payroll> p=repo.findByBranchId(branchId,PageRequest.of(Math.max(page,0),s,Sort.by("year").descending().and(Sort.by("month").descending())));return page(p);}List<Payroll> a=(month!=null&&year!=null)?repo.findByMonthAndYear(month,year):repo.findAll();int from=Math.min(Math.max(page,0)*s,a.size()),to=Math.min(from+s,a.size());List<Payroll> sub=from<to?a.subList(from,to):List.of();return new PageResponse<>(sub.stream().map(mapper::toResponse).toList(),page,s,a.size(),(int)Math.ceil(a.size()/(double)s));}
 private PageResponse<PayrollResponse> page(Page<Payroll> p){return new PageResponse<>(p.getContent().stream().map(mapper::toResponse).toList(),p.getNumber(),p.getSize(),p.getTotalElements(),p.getTotalPages());}
 public PayrollResponse get(Long id){return repo.findById(id).map(mapper::toResponse).orElseThrow(()->new ResourceNotFoundException("Payroll not found: "+id));}public List<PayrollResponse> staffPayroll(Long id){return repo.findByStaffIdOrderByYearDescMonthDesc(id).stream().map(mapper::toResponse).toList();}
 @Transactional public PayrollResponse update(Long id,GeneratePayrollRequest r,Long actor){Payroll p=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Payroll not found: "+id));validation.beforeUpdate(p);if(r.paymentMode()!=null)p.setPaymentMode(parse(r.paymentMode()));p.setRemarks("Updated before payment");p.setGeneratedBy(actor);return mapper.toResponse(repo.save(p));}
 public SalaryCreditResponse credit(Long id,String mode,Long actor){return credit.credit(id,mode,actor);}public List<SalaryCreditResponse> creditAll(Integer m,Integer y,String mode,Long actor){return credit.creditAll(m,y,mode,actor);}public SalaryCreditResponse retry(Long id,Long actor){return credit.retry(id,actor);}public SalaryCreditResponse paymentStatus(Long id){Payroll p=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Payroll not found: "+id));return new SalaryCreditResponse(id,p.getStaffId(),p.getNetSalary(),p.getPaymentStatus().name(),p.getTransactionId(),"Current payment status");}public PageResponse<PayrollResponse> branchPayroll(Long b,int page,int size){return search(null,null,b,page,size);}private PaymentMode parse(String s){try{return PaymentMode.valueOf((s==null?"BANK_TRANSFER":s).toUpperCase());}catch(Exception e){throw new BusinessRuleException("Invalid payment mode");}}private int n(Integer x){return x==null?0:x;}
}
