package com.agacostays.payment.service.impl;

import com.agacostays.payment.audit.*; import com.agacostays.payment.client.*; import com.agacostays.payment.dto.request.*; import com.agacostays.payment.dto.response.*; import com.agacostays.payment.entity.*; import com.agacostays.payment.enums.*; import com.agacostays.payment.exception.*; import com.agacostays.payment.idempotency.IdempotencyService; import com.agacostays.payment.mapper.PaymentMapper; import com.agacostays.payment.producer.PaymentEventProducer; import com.agacostays.payment.repository.*; import com.agacostays.payment.security.*; import com.agacostays.payment.service.*; import com.agacostays.payment.validation.PaymentValidationService; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.Instant; import java.util.*;

@Service @Transactional
public class PaymentServiceImpl implements PaymentService {
 private final PaymentRepository payments; private final PaymentTransactionRepository transactions; private final PaymentMapper mapper; private final PaymentGatewayService gateway; private final PaymentVerificationService verifier; private final PaymentValidationService validation; private final CurrentUserProvider current; private final BranchAccessValidator branchAccess; private final OwnerAccessValidator ownerAccess; private final BookingServiceClient bookings; private final RestaurantServiceClient restaurant; private final BillingServiceClient billing; private final NotificationServiceClient notification; private final PaymentEventProducer events; private final IdempotencyService idempotency; private final PaymentAuditHelper audit; private final boolean allowRequestAmount;
 public PaymentServiceImpl(PaymentRepository payments,PaymentTransactionRepository transactions,PaymentMapper mapper,PaymentGatewayService gateway,PaymentVerificationService verifier,PaymentValidationService validation,CurrentUserProvider current,BranchAccessValidator branchAccess,OwnerAccessValidator ownerAccess,BookingServiceClient bookings,RestaurantServiceClient restaurant,BillingServiceClient billing,NotificationServiceClient notification,PaymentEventProducer events,IdempotencyService idempotency,PaymentAuditHelper audit,@org.springframework.beans.factory.annotation.Value("${payment.validation.allow-request-amount:true}") boolean allowRequestAmount){this.payments=payments;this.transactions=transactions;this.mapper=mapper;this.gateway=gateway;this.verifier=verifier;this.validation=validation;this.current=current;this.branchAccess=branchAccess;this.ownerAccess=ownerAccess;this.bookings=bookings;this.restaurant=restaurant;this.billing=billing;this.notification=notification;this.events=events;this.idempotency=idempotency;this.audit=audit;this.allowRequestAmount=allowRequestAmount;}
 public PaymentResponse createPayment(CreatePaymentRequest r,String key){ensureCreateAccess();validation.validateCreate(r.amount(),r.paymentFor());branchAccess.validate(r.branchId()); Long customer=resolveCustomer(); BookingResponse b=null; BigDecimal amount=r.amount(); if(r.paymentFor()==PaymentFor.BOOKING){b=bookings.getBooking(Long.valueOf(r.referenceId())); if(b.branchId()!=null&&!b.branchId().equals(r.branchId()))throw new BusinessRuleException("Booking branch mismatch"); if(b.customerId()!=null&&current.hasRole("CUSTOMER")&&b.customerId()!=customer)throw new AccessDeniedException("Booking does not belong to customer"); if(!allowRequestAmount && b.amount()!=null) amount=b.amount(); }
  if(amount.signum()<=0) throw new BusinessRuleException("Server-side payment amount could not be resolved");
  return createInternal(r.branchId(),r.paymentFor(),r.referenceId(),amount,r.currency(),r.paymentMethod(),customer,key);
 }
 public PaymentResponse createRestaurantPayment(RestaurantPaymentRequest r,String key){ensureCreateAccess();branchAccess.validate(r.branchId()); Long customer=resolveCustomer(); var o=restaurant.getOrder(r.orderId()); if(o.branchId()!=null&&!o.branchId().equals(r.branchId()))throw new BusinessRuleException("Restaurant order branch mismatch"); if(o.customerId()!=null&&current.hasRole("CUSTOMER")&&o.customerId()!=customer)throw new AccessDeniedException("Restaurant order does not belong to customer"); if(!allowRequestAmount && o.amount()!=null && o.amount().signum()>0 && !r.amount().setScale(2).equals(o.amount().setScale(2))) throw new BusinessRuleException("Restaurant order amount mismatch"); return createInternal(r.branchId(),PaymentFor.RESTAURANT_ORDER,r.orderId(),allowRequestAmount?r.amount():o.amount(),r.currency(),PaymentMethod.RAZORPAY,customer,key);}
 public PaymentResponse createFinalBillPayment(FinalBillPaymentRequest r,String key){ensureCreateAccess();branchAccess.validate(r.branchId()); Long customer=resolveCustomer(); var b=billing.getFinalBill(r.bookingId()); if(b.branchId()!=null&&!b.branchId().equals(r.branchId()))throw new BusinessRuleException("Final bill branch mismatch"); if(b.customerId()!=null&&current.hasRole("CUSTOMER")&&b.customerId()!=customer)throw new AccessDeniedException("Final bill does not belong to customer"); if(!allowRequestAmount && b.finalAmount()!=null && b.finalAmount().signum()>0 && !r.amount().setScale(2).equals(b.finalAmount().setScale(2))) throw new BusinessRuleException("Final bill amount mismatch"); return createInternal(r.branchId(),PaymentFor.FINAL_BILL,String.valueOf(r.bookingId()),allowRequestAmount?r.amount():b.finalAmount(),r.currency(),PaymentMethod.RAZORPAY,customer,key);}
 private PaymentResponse createInternal(Long branchId,PaymentFor forType,String ref,BigDecimal amount,String currency,PaymentMethod method,Long customer,String key){CreatePaymentRequest req=new CreatePaymentRequest(branchId,forType,ref,amount,currency,method);var existing=idempotency.findExisting(key,req,payments);if(existing.isPresent())return mapper.toResponse(existing.get()); var gatewayOrder=gateway.createOrder(amount,currency,ref); var p=Payment.builder().branchId(branchId).paymentFor(forType).referenceId(ref).customerId(customer).amount(amount.setScale(2,RoundingMode.HALF_UP)).currency(currency).paymentMethod(method).paymentStatus(PaymentStatus.PENDING).gatewayName(PaymentGatewayName.valueOf(gatewayOrder.gatewayName())).gatewayOrderId(gatewayOrder.gatewayOrderId()).createdAt(Instant.now()).updatedAt(Instant.now()).build();p=payments.save(p);transactions.save(PaymentTransaction.builder().paymentId(p.getPaymentId()).transactionType("CREATED").amount(p.getAmount()).status("PENDING").createdAt(Instant.now()).build());idempotency.save(key,req,p.getPaymentId());audit.log(new AuditLogRequest("PAYMENT_CREATED",current.userId(),p.getPaymentId(),"for="+forType+",reference="+ref));return mapper.toResponse(p);}
 public VerifyPaymentResponse verifyPayment(VerifyPaymentRequest r){return verify(r,PaymentFor.BOOKING);}
 public VerifyPaymentResponse verifyRestaurantPayment(VerifyPaymentRequest r){return verify(r,PaymentFor.RESTAURANT_ORDER);}
 private VerifyPaymentResponse verify(VerifyPaymentRequest r,PaymentFor expected){Payment p=payments.findFirstByGatewayOrderId(r.gatewayOrderId()).orElseThrow(()->new ResourceNotFoundException("Payment not found for gateway order"));ownerAccess.validate(p);if(p.getPaymentFor()!=expected)throw new BusinessRuleException("Payment type mismatch");verifier.verify(p,r);if(p.getPaymentStatus()!=PaymentStatus.SUCCESS){p.setGatewayPaymentId(r.gatewayPaymentId());p.setGatewaySignature(r.gatewaySignature());p.setPaymentStatus(PaymentStatus.SUCCESS);p.setPaidAt(Instant.now());payments.save(p);transactions.save(PaymentTransaction.builder().paymentId(p.getPaymentId()).transactionType("CAPTURE").amount(p.getAmount()).gatewayTransactionId(r.gatewayPaymentId()).status("SUCCESS").createdAt(Instant.now()).build());events.paymentSuccess(new com.agacostays.payment.event.PaymentSuccessEvent("PaymentSuccess",1,Instant.now(),p.getPaymentId(),p.getCustomerId(),p.getBranchId(),p.getReferenceId(),p.getAmount(),p.getPaymentFor().name(),p.getGatewayPaymentId(),UUID.randomUUID().toString()));notification.notifyPayment(p.getCustomerId(),"Payment successful for "+p.getReferenceId());}return new VerifyPaymentResponse(true,mapper.toResponse(p));}
 @Transactional(readOnly=true) public PaymentResponse get(Long id){Payment p=payments.findById(id).orElseThrow(()->new ResourceNotFoundException("Payment not found: "+id));ownerAccess.validate(p);return mapper.toResponse(p);}
 @Transactional(readOnly=true) public PageResponse<PaymentResponse> myPayments(Pageable p){long cid=current.customerId();return page(payments.findByCustomerIdOrderByCreatedAtDesc(cid,p));}
 @Transactional(readOnly=true) public PageResponse<PaymentResponse> bookingPayments(Long bookingId,Pageable p){return referencePayments(String.valueOf(bookingId),PaymentFor.BOOKING,p);}
 @Transactional(readOnly=true) public PageResponse<PaymentResponse> restaurantOrderPayments(String orderId,Pageable p){return referencePayments(orderId,PaymentFor.RESTAURANT_ORDER,p);}
 private PageResponse<PaymentResponse> referencePayments(String reference,PaymentFor forType,Pageable p){var list=payments.findByReferenceIdOrderByCreatedAtDesc(reference).stream().filter(x->x.getPaymentFor()==forType).map(mapper::toResponse).toList(); if(current.hasRole("CUSTOMER"))list=list.stream().filter(x->x.customerId().equals(current.customerId())).toList(); return new PageResponse<>(list,p.getPageNumber(),p.getPageSize(),list.size(),list.isEmpty()?0:1,true);}
 @Transactional(readOnly=true) public PageResponse<PaymentResponse> branchPayments(Long branchId,Pageable p){if(!(current.hasRole("MANAGER")||current.hasRole("ROOT_ADMIN")||current.hasRole("SYSTEM")))throw new AccessDeniedException("Branch payment listing is restricted to manager/root admin/system");branchAccess.validate(branchId);return page(payments.findByBranchIdOrderByCreatedAtDesc(branchId,p));}
 private PageResponse<PaymentResponse> page(Page<Payment> page){return new PageResponse<>(page.getContent().stream().map(mapper::toResponse).toList(),page.getNumber(),page.getSize(),page.getTotalElements(),page.getTotalPages(),page.isLast());}
 private void ensureCreateAccess(){if(!(current.hasRole("CUSTOMER")||current.hasRole("RECEPTIONIST")||current.hasRole("MANAGER")||current.hasRole("ROOT_ADMIN")||current.hasRole("SYSTEM")))throw new AccessDeniedException("Payment creation is not allowed for this role");}
 private Long resolveCustomer(){if(current.hasRole("CUSTOMER"))return current.customerId();if(current.userId()!=0)return current.userId();throw new AccessDeniedException("Customer identity could not be resolved");}
}
