spring.datasource.url=jdbc:h2:mem:notificationdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
spring.kafka.bootstrap-servers=localhost:9092
notification.jwt.secret=VGhpcy1kZXYtc2VjcmV0LW11c3QtYmUtcmVwbGFjZWQtd2l0aC1hLXN0cm9uZy1zZWNyZXQ=
